name: Preview Build

on:
  push: 
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    # env:
    #   PULL_REQUEST_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.0'
          registry-url: https://registry.npmjs.com/

      - name: Install and Build
        env: 
          VITE_HF_KEY: ${{secrets.VITE_HF_KEY}}
        run: yarn install && yarn run build --base=/vue_chart_1/
        

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist