name: Preview Build

on:
  push: 
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.0'
          registry-url: https://registry.npmjs.com/

      - name: Set environment variables
        run:  |
          echo "VITE_HF_KEY=${{ secrets.VITE_HF_KEY }}" >> $GITHUB_ENV
          echo "VITE_AMAP_IP_KEY=${{ secrets.VITE_AMAP_IP_KEY }}" >> $GITHUB_ENV

      - name: Install and Build
        run: yarn install && yarn run build --base=/vue_chart_1/
        env:
          VITE_HF_KEY: ${{ secrets.VITE_HF_KEY }}
          VITE_AMAP_IP_KEY: ${{secrets.VITE_AMAP_IP_KEY}}
        

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist